### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by driskerr** [alexchoo1/sql-scratch-capstone-turn-in#3]
## Rubric Score
 
### Criteria 1: Report:
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_  Every answer has three components: 1) SQL queries, 2) query output as evidence, 3) text interpreting the query results. Some particularly nice touches include the table of contents breaking down all the questions will be answering and your text interpreting the query results.
 
### Criteria 2: Query Accuracy:
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ All queries accurately retrieve the data as intended. You are exceptionally skilled at creating all the entire funnel with % conversion within your queries.
 
### Criteria 3: Query Formatting
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ You succeed at formatting your queries. Queries adhere to at least 7 rules
of the [style guide](https://s3.amazonaws.com/codecademy-content/programs/learn-sql-from-scratch/SQL+Style+Guide+for+Learn+SQL+from+Scratch.pdf). An area for improvement is to capitalize your SQL keywords like `SELECT`, `FROM`.

### Criteria 4: Understanding underlying concepts and terminology
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ Terms are used correctly throughout the report. You also make good connections between the drop-off rates in the quiz funnel and real user behavior (like not having an eye exam recently). You also did a good job of tying these findings to suggestions for improvement for Warby Parker's business.

 ### Overall Score: 16/16
Overall, very well done! Your report provides plenty of supporting evidence for your claims with these well-written queries. I am most impressed by your ability to write complex queries and interpret the results in a meaningful way. There is some area of improvement in the formatting of your queries (like capitalization). Your slides demonstrate a firm understanding of the real-world behaviors that the data refers to. Great work!

**Comment by alexchoo1** [comment]
Thank you! I appreciate your feedback.
